"""Markdown for docs/voa-inventory.md."""

from collections import Counter
from datetime import date

from voa_inventory.rows import MIN_WORDS, Row, count_usable
from voa_inventory.topics import Catalog

NEEDED = 2


def table(header: list[str], body: list[list[str]]) -> list[str]:
    return [
        "| " + " | ".join(header) + " |",
        "|" + "---|" * len(header),
        *("| " + " | ".join(row) + " |" for row in body),
    ]


def topic_table(rows: list[Row], catalog: Catalog, coverage: float) -> tuple[list[str], list[str]]:
    lines, short = [], []
    header = [
        "Unit",
        "Topic",
        "Level 4",
        "Levels 4-5",
        "Any level",
        "Est. whole site, level 4",
        "Verdict",
    ]
    for t in catalog.topics:
        counts, _ = count_usable(rows, t.id)
        if counts.level4 >= NEEDED:
            verdict = "enough"
        else:
            short.append(t.id)
            verdict = "SWAP" if coverage >= 1 else f"fewer than {NEEDED} in sample"
        est = f"{counts.level4 / coverage:.0f}" if coverage else "?"
        lines.append([
            str(t.unit), f"{t.label} (`{t.id}`)", str(counts.level4), str(counts.levels45),
            str(counts.any_level), est, verdict,
        ])  # fmt: skip
    return table(header, lines), short


def candidate_table(rows: list[Row], catalog: Catalog) -> list[str]:
    ranked = []
    for t in catalog.candidates:
        counts, pool = count_usable(rows, t.id, candidate=True)
        ranked.append((counts, t, pool))
    ranked.sort(key=lambda x: (-x[0].level4, -x[0].any_level, x[1].id))
    body = []
    for counts, t, pool in ranked:
        examples = "<br>".join(f"[{r.item.title[:60]}]({r.item.url})" for r in pool[:2])
        body.append([
            f"{t.label} (`{t.id}`)", str(counts.level4), str(counts.levels45),
            str(counts.any_level), examples,
        ])  # fmt: skip
    return table(["Candidate", "Level 4", "Levels 4-5", "Any level", "Examples"], body)


def level_matrix(rows: list[Row], catalog: Catalog) -> list[str]:
    usable = [r for r in rows if r.usable]
    body = []
    levels: list[int | None] = [*range(1, 8), None]
    for lv in levels:
        pool = [r for r in usable if r.level == lv]
        cells = [str(sum(t.id in r.topics for r in pool)) for t in catalog.topics]
        body.append(
            [str(lv or "unknown"), *cells, str(sum(not r.topics for r in pool)), str(len(pool))]
        )
    return table(["Level", *[t.id for t in catalog.topics], "no topic", "Total"], body)


def render_md(
    rows: list[Row], meta: dict, catalog: Catalog, tagger_name: str, evaluation: str = ""
) -> str:
    total_urls = meta.get("sitemap_urls", 0)
    coverage = len(rows) / total_urls if total_urls else 0.0
    usable = [r for r in rows if r.usable]
    would_be = [r for r in rows if r.item.has_audio and r.item.word_count >= MIN_WORDS]
    reasons = Counter(",".join(r.item.license_reasons) or "ok" for r in would_be)
    topic_lines, short = topic_table(rows, catalog, coverage)
    programs = Counter(r.item.program or "(none)" for r in rows)
    prog_usable = Counter(r.item.program or "(none)" for r in usable)
    prog_rows = [[p, str(n), str(prog_usable[p])] for p, n in programs.most_common(15)]
    swap = "\n".join(f"- `{t}`" for t in short) or "- none"
    partial = (
        f"""**Partial crawl.** Only {coverage:.1%} of the site is sampled. "Fewer than {NEEDED} in
sample" therefore does not show that the corpus lacks items, only that this sample is too
small to show them; "SWAP" appears only at 100% coverage. Continue with `make voa-crawl`."""
        if coverage < 1
        else ""
    )
    return f"""# VOA Learning English inventory

Generated by `python -m voa_inventory.report` on {date.today().isoformat()}; do not edit by
hand. Metadata only: `data/voa_inventory.csv` holds one row per page (URL, title, dates,
counts, flags), never article text or audio.

## Coverage

- The site's sitemaps list **{total_urls}** article URLs. This inventory parsed
  **{len(rows)}** of them (**{coverage:.1%}**), visited in a fixed random order
  (seed {meta.get("seed", "?")}), so the sample is uniform and every count below is a lower
  bound on the whole site. "Est. whole site" divides by the coverage: a rough scale, not a
  count.
- Pages with text of at least {MIN_WORDS} words and audio: {len(would_be)}.
  **Usable** (also licence_ok): **{len(usable)}**. The CSV column `usable` is 1 for exactly
  these rows; every count in this file is over usable rows only.

**Usable** means: VOA-staff byline, no wire credit or mention (AP, Reuters, AFP), no
third-party image credit, an audio file on the page, and at least {MIN_WORDS} words of body text.
The filter is conservative on purpose (`license.py`); P50 re-checks every item it ingests.

Licence outcome of the {len(would_be)} pages with audio and enough text:

{chr(10).join(table(["Reasons", "Pages"], [[k, str(v)] for k, v in reasons.most_common()]))}

## Level 4 candidate topics

Level is a coarse heuristic (`levels.py`): *Let's Learn English* lessons by programme
level, everything else by Flesch-Kincaid grade (below 7 is level 4, 7-9 level 5, 9-11
level 6, above level 7). Topics come from the **{tagger_name}** tagger (`topics.yaml`) on
each page's title and first paragraph. Counts are usable items.

{chr(10).join(topic_lines)}

{evaluation}
### Topics with fewer than {NEEDED} usable items with audio at level 4

{swap}

{partial}

ADR-0006: a topic without items is swapped, never written. Replacement candidates,
scored the same way (usable items in the sample; examples are level 4, else any level):

{chr(10).join(candidate_table(rows, catalog))}

## Level by topic (usable items)

{chr(10).join(level_matrix(rows, catalog))}

An item can carry several topics with the phrase tagger and at most one with the embedding
tagger, so a row can sum to more than its total.

## Programmes (top 15 by pages)

{chr(10).join(table(["Programme", "Pages", "Usable"], prog_rows))}

## Reproduce

```bash
export VOA_CONTACT_EMAIL=you@example.com   # sent in the User-Agent
make voa-crawl ARGS="--limit 3000"         # resumable, 1 request per second
make voa-report                            # offline; rewrites this file and the CSV
```
"""
